### ISSUE TITLE
GPL License Request

### ISSUE THREAD

**Issue by hexylena** [erasche/chado-jbrowse-connector#4]
Hi @abretaud @satta,

@njbooher would like to re-use code from this project in a drupal module. There are concerns in the drupal community that this would force others to open up private drupal modules as well, and he emailed me inquiring about this.

[Here](https://github.com/isubit/tripal_jbrowse_api) is the module in question, and [here](https://github.com/isubit/tripal_jbrowse_api/blob/master/includes/tripal_jbrowse_api.queries.inc) are some of the queries which have been re-used from `sql.go`.

I licensed this originally under the AGPLv3 because I'm a software freedom proponent especially for SaaS projects where it might be made private.

Here are two options for the project, and I'd like your feedback (and consent or not) on the options.
- We grant him a license exception for the drupal module in question
- We re-license the project under a different license, perhaps the GPL or similar, but that would lack the network access provisions.

I've now spent an hour or so reading FSF docs and faqs and licensing law, and I am caring less every minute, so at this point, I'm pretty completely open to suggestions. <s>Especially given that I have secret desires to replace tripal completely someday.</s>

Again, if you have feedback on this, please provide it, and your consents to go in whichever directions you're OK with.

Cheers

**Comment by satta** [comment]
TBH I must say that as far as licenses go, for me ease and spread of adoption usually beats collective freedom, and in fact I tend to pick permissive licenses for my own projects. From my point of view, I would be OK with relaxing the license to not include the network access provision.

That being said, @erasche has a point as well (and also written the majority of the code ;)) so I'd also be happy with a simple exception.

**Comment by abretaud** [comment]
I usually like agpl for this kind of project, but if it's blocking for @njbooher and the drupal community, I have no problem with any of the two options.
I have a little preference for the exception, but I don't how this can be done exactly to be valid from a lawyer point of vue

**Comment by hexylena** [comment]
Ok, it sounds like we'd use an exception here since that seems amenable to everyone. That would be accomplished by granting a separate license to @njbooher (similar to how some commercial projects are GPLv3 + commercial license).

@njbooher to fulfil this portion I will email you a copy of this software with a GPLv3 license included. You are then free to use that at your discretion and will allow you to license your drupal plugin as GPL as well.
